### ISSUE TITLE
Variables within @range don't persist

### ISSUE THREAD

**Issue by odunbar** [JuliaGPU/NVTX.jl#28]
Using 
```julia
NVTX.@range a,b,c = func()
a
```
or 
```julia
NVTX.@range begin
     a,b,c = func()
end
a
```
leads to `undefined variable a` error in subsequent line.

While the following seems to work
```julia 
a,b,c = NVTX.@range func()
a
```

**Comment by simonbyrne** [comment]
So the problem is we wrap the block in a `try`/`finally` block, which introduces a new scope. There's not a great fix, absent https://github.com/JuliaLang/julia/pull/39217.

For now we can use `Expr(:tryfinally,...)` which has this scary warning:
https://github.com/JuliaLang/julia/blob/242cdc5f6c06aaba99315bfcd41f8884ccc445a6/base/timing.jl#L196-L204
but it is used in other packages, e.g. [TimerOutputs.jl](https://github.com/KristofferC/TimerOutputs.jl/blob/30b510efe435f7c3d9cf004f4d970676c8801887/src/TimerOutput.jl#L237)
